# Generated by Django 3.2 on 2022-08-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapi', '0002_alter_project_id'),
        ('issueapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectapi.project'),
            preserve_default=False,
        ),
    ]
