# Generated by Django 3.2 on 2022-08-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueapi', '0002_issue_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
