# Generated by Django 3.2 on 2022-08-31 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueapi', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issueapi.status'),
            preserve_default=False,
        ),
    ]
