# Generated by Django 3.2 on 2022-08-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueapi', '0004_issue_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
