# Generated by Django 3.2 on 2022-08-31 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueapi', '0005_alter_status_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project_title',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status_id',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
