# Generated by Django 3.2 on 2022-08-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueapi', '0006_auto_20220831_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project_title',
            new_name='project',
        ),
    ]
